blank_issues_enabled: false
contact_links:
  - name: 💬 Question / Discussion
    url: https://github.com/lishLRF/step-bbox-parser/discussions
    about: Ask questions and discuss ideas in Discussions.
